# Generated by Django 4.0.4 on 2022-04-29 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('nome_social', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.IntegerField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_social', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frase', models.TextField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('produto', models.TextField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto_data', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('total_receber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('produto', models.TextField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto_data', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images/')),
                ('texto', models.TextField(max_length=200)),
                ('link', models.URLField(max_length=50)),
                ('auto_data', models.DateField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.administrador')),
            ],
        ),
    ]
