# Generated by Django 4.0.4 on 2022-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_administrador_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receita',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
