# Generated by Django 4.0.4 on 2022-05-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_despesas_recorrente_receita_recorrente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='name_social',
            new_name='nome_social',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='blog',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.administrador'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfil'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfil'),
        ),
    ]
