# Generated by Django 4.0.4 on 2022-05-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_name_social_perfil_nome_social_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='despesas',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
