# Generated by Django 4.0.4 on 2022-05-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blog_administrador_remove_despesas_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='nome_social',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='auto_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='texto',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='auto_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='produto',
            field=models.CharField(max_length=50, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='recorrente',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Recorrente'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='total_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='auto_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='produto',
            field=models.CharField(max_length=50, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='recorrente',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Recorrente'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='total_receber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
