# Generated by Django 4.0.4 on 2022-05-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_despesas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=None, editable=False, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='total_receber',
            field=models.DecimalField(decimal_places=2, default=None, editable=False, max_digits=10, verbose_name='Total'),
        ),
    ]
